using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ExtTs.ExtTypes {
	[Serializable]
	[Flags]
	public enum SpecialParamMatch {
		NONE								= 0,
		
		STANDARD_COLLECTION_FUNC			= 1,
		STANDARD_COLLECTION_FUNC_ARR		= 2,
		STANDARD_COLLECTION_OBJECT			= 4,
		STANDARD_COLLECTION_OBJECT_ARR		= 8, 
		STANDARD_COLLECTION_INTERFACE		= 16,
		STANDARD_COLLECTION_INTERFACE_ARR	= 32,
		
		SPREAD_COLLECTION_FUNC				= 64,
		SPREAD_COLLECTION_OBJECT			= 128,
		SPREAD_COLLECTION_INTERFACE			= 256,

		ANY_FUNC			= STANDARD_COLLECTION_FUNC | SPREAD_COLLECTION_FUNC,
		ANY_OBJECT			= STANDARD_COLLECTION_OBJECT | SPREAD_COLLECTION_OBJECT,
		ANY_INTERFACE		= STANDARD_COLLECTION_INTERFACE | SPREAD_COLLECTION_INTERFACE,

		ANY_ARR				= STANDARD_COLLECTION_FUNC_ARR | STANDARD_COLLECTION_OBJECT_ARR | STANDARD_COLLECTION_INTERFACE_ARR,
		ANY_SPREAD			= SPREAD_COLLECTION_FUNC | SPREAD_COLLECTION_OBJECT | SPREAD_COLLECTION_INTERFACE,

	}
}
