using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ExtTs.ExtTypes.Enums {
	[Flags]
	[Serializable]
	public enum TypeDefinitionPlace {
		UNKNOWN						= 0,
		CONFIGURATION				= 1,
		PROPERTY					= 2,

		EVENT_PARAM					= 4,
		EVENT_PARAM_CALLBACK_PARAM	= 8,
		EVENT_PARAM_CALLBACK_RETURN	= 16,
		EVENT_PARAM_CFGOBJ_PROP		= 32,

		METHOD_PARAM				= 64,
		METHOD_PARAM_CALLBACK_PARAM	= 128,
		METHOD_PARAM_CALLBACK_RETURN= 256,
		METHOD_PARAM_CFGOBJ_PROP	= 512,
		
		EVENT_RETURN				= 1024,
		METHOD_RETURN				= 2048,

		ANY_PROPERTY				= CONFIGURATION | PROPERTY | EVENT_PARAM_CFGOBJ_PROP | METHOD_PARAM_CFGOBJ_PROP,
		ANY_PARAM					= METHOD_PARAM | EVENT_PARAM | EVENT_PARAM_CALLBACK_PARAM | METHOD_PARAM_CALLBACK_PARAM,
		ANY_RETURN					= EVENT_RETURN | METHOD_RETURN | EVENT_PARAM_CALLBACK_RETURN | METHOD_PARAM_CALLBACK_RETURN,
	}
}
